### ISSUE TITLE
How long will it take to install?

### ISSUE THREAD

**Issue by Wikunia** [Hirse/brackets-ungit#1]
Hey Jan,

thanks for the neat extension idea. It already takes about 5 minutes to install. Is this normal?

Cheers,

Ole

**Comment by Wikunia** [comment]
Update:
I hided the window and reloaded Brackets and it works now! 
A bit unexpected that the loading brackets sign doesn't disappear after the install process finished.

**Comment by Hirse** [comment]
Thanks, happy you like it.

The installation is doing `npm install` so it might depend on your connection speed.
You can click on the (yellow) toolbar icon to open the install log.

If you don't see any progress there, you could also close Brackets and run `npm install` in the extension directory yourself.

Let me know if it works.

**Comment by Hirse** [comment]
You are right, I should include some indication in the Dialog that the process has finished.

What does happen right now, is that the Toolbar Icon turns gray and the tooltip on the button changes.

**Comment by Wikunia** [comment]
Sorry I have absolutely no idea :D I just waited and there were no additional log lines for a while so I reloaded Brackets ;)

**Comment by Hirse** [comment]
I have added some more status information in the last few commits.
If you like, you can install the source from GitHub and try it out.
In any case, I plan to update the released extension in a while when I have done some more testing myself.

**Comment by Hirse** [comment]
New release is done, you will get a notification when the installation is complete.
