### ISSUE TITLE
A new version of ungit (0.10.0) is available! Run sudo -H npm update -g ungit to install. (You are currently running version 0.9.3.)

### ISSUE THREAD

**Issue by zeg-io** [Hirse/brackets-ungit#6]
I keep getting the above warning.

However, when I run the command, and my version is updated, the ungit extension seems to ignore it... OR the ungit extension is looking at some other installation?

**Comment by zeg-io** [comment]
It would seem you are installing a version of ungit within the extension which is not being updated

**Comment by zeg-io** [comment]
...and version 0.10.0 doesn't work with the extension

**Comment by Hirse** [comment]
The extension is running the locally installed version of ungit.
With the command in your title you are installing the new version globally.

To update the used version change the entry in the package.json and run `npm update`.

**Comment by basbebe** [comment]
will the brackets extension be updated to use the new version?

**Comment by zeg-io** [comment]
Hirse,  when the version is updated it doesn't work with the extension, it crashes.  I had to revert to 0.9.3

**Comment by Hirse** [comment]
@zeg-io Thanks for testing this.
@bax- based on @zeg-io's experience I am not going to update right now.

**Comment by Hirse** [comment]
Please install from Git or npm for an updated version.
Release to Brackets Extension Registry should follow shortly. (There are currently some issues: https://github.com/adobe/brackets/issues/13403.)
