### ISSUE TITLE
Installation error on Brackets (1.6)

### ISSUE THREAD

**Issue by terraconnect** [Hirse/brackets-ungit#7]
Sadly the extension cannot be installed, yielding an error.

![image](https://cloud.githubusercontent.com/assets/4715265/13140851/ba7fd166-d634-11e5-8084-2140793cc05c.png)

**Comment by Hirse** [comment]
Can you see any error message in the developer tools?

**Comment by terraconnect** [comment]
Hi Hirse, here's what we have:
![image](https://cloud.githubusercontent.com/assets/4715265/13213026/2ce01612-d946-11e5-806c-9d071896c36b.png)

**Comment by Hirse** [comment]
Can you try to install from the GitHub source to see if the fix is working, please?

**Comment by terraconnect** [comment]
Hi Hirse!

The installation went through successfully as you can see from the first image below.

But the extension does not work: toggling the ungit view does not work as you can see on the gif. 

Note that clicking the toggle button does not lead to new errors in the console.
Finally, Brackets is unable to restart. I have the white screen of death and have to terminate the process. 

![image](https://cloud.githubusercontent.com/assets/4715265/13429194/512f01d4-dfbf-11e5-91aa-a846cc5f800f.png)

![animation 6](https://cloud.githubusercontent.com/assets/4715265/13429261/ab806de4-dfbf-11e5-8179-32cb0c524335.gif)

**Comment by JoseDeza** [comment]
Same issue here in Brackets,
Successful Ungit extension installation
No errors
Idle "Toggle Ungit View" process...

Note that Ungit is working perfectly on the same system when started from:
- bash
- Visual Studio Code / Ungit extension
